export const countryFlagMap: { [key: string]: string } = {
    'Brazil': 'BR',
    'United States': 'US',
    'Germany': 'DE',
    'Argentina': 'AR',
    'France': 'FR',
    'Spain': 'ES',
    'Colombia': 'CO',
    'Canada': 'CA',
    'Mexico': 'MX',
    'Chile': 'CL',
    'Peru': 'PE',
    'Venezuela': 'VE',
    'Italy': 'IT',
    'Portugal': 'PT',
    'Netherlands': 'NL',
    'Belgium': 'BE',
    'Poland': 'PL',
    'Sweden': 'SE',
    'Russia': 'RU',
    'Ukraine': 'UA',
    'Greece': 'GR',
    'Uruguay': 'UY',
    'England': 'GB',    
    'Croatia': 'HR',    
    'Serbia': 'RS',  
    'Denmark': 'DK',    
    'Norway': 'NO',     
    'Switzerland': 'CH', 
    'Turkey': 'TR',    
    'Cameroon': 'CM',  
    'Nigeria': 'NG',   
    'Egypt': 'EG',   
    'South Africa': 'ZA', 
    'Algeria': 'DZ',    
    'Ivory Coast': 'CI', 
    'Japan': 'JP',      
    'South Korea': 'KR', 
    'Iran': 'IR',       
    'Australia': 'AU',  
    'New Zealand': 'NZ', 
    'Saudi Arabia': 'SA', 
    'Qatar': 'QA',      
    'Morocco': 'MA',    
    'Tunisia': 'TN',    
    'Costa Rica': 'CR',
    'Paraguay': 'PY',  
    'Honduras': 'HN',  
    'Ecuador': 'EC',   
    'Bolivia': 'BO',    
    'Syria': 'SY',      
    'Iraq': 'IQ',       
    'Jordan': 'JO',     
    'Palestine': 'PS', 
};
